#include "declarations.h"

void showMenuPrimary() {
    printf(
        "\n"
        " +========================================================+\n"
        " |                 GERENCIADOR DE LISTAS                  |\n"
        " +===========================+============================+\n"
        " | LEITURA & BUSCA           | INSERCAO                   |\n"
        " |  1. Ler encadeada         |  7. Fim encadeada          |\n"
        " |  2. Ler simples           |  8. Fim simples            |\n"
        " |  3. Busca RG encadeada    |  9. Inicio encadeada       |\n"
        " |  4. Busca RG simples      | 10. Inicio simples         |\n"
        " |  5. Exibir encadeada      | 11. Meio encadeada         |\n"
        " |  6. Exibir simples        | 12. Meio simples           |\n"
        " |                           |                            |\n"
        " | ARQUIVOS                  | REMOCAO                    |\n"
        " | 20. Salvar encadeada      | 13. Posicao sequencial     |\n"
        " | 21. Salvar sequencial     | 14. Posicao encadeada      |\n"
        " +===========================+============================+\n"
        " | COMPARACOES (ENCADEADA x SEQUENCIAL)                   |\n"
        " | 15. Tempo de leitura      | 18. Ins. fim paralela      |\n"
        " | 16. Remocao paralela      | 19. Ins. meio paralela     |\n"
        " | 17. Ins. inicio paralela  |                            |\n"
        " +===========================+============================+\n"
        " | 167. Sair                                              |\n"
        " +========================================================+\n"
        " Escolha uma opcao: "
    );
}