#include "declarations.h"

void showMenuPrimary() {
    printf(
        "\n"
        " +==========================================================================================+\n"
        " |               SISTEMA DE AVALIACAO DE ESTRUTURAS DE DADOS E ALGORITMOS                   |\n"
        " |            Comparativo: Lista Encadeada Dinamica vs Vetor Sequencial Contiguo            |\n"
        " +==========================================================================================+\n"
        " | [ CARGA, VISUALIZACAO E EXPORTACAO DE DADOS ]                                            |\n"
        " |   1. Ler arquivo -> Lista Encadeada                                                      |\n"
        " |   2. Ler arquivo -> Lista Sequencial                                                     |\n"
        " |   5. Imprimir todos os registros da Lista Encadeada no console                           |\n"
        " |   6. Imprimir todos os registros da Lista Sequencial no console                          |\n"
        " |  20. Exportar Lista Encadeada atual para um arquivo de texto (.txt)                      |\n"
        " |  21. Exportar Lista Sequencial atual para um arquivo de texto (.txt)                     |\n"
        " +==========================================================================================+\n"
        " | [ OPERACOES DE MANIPULACAO INDIVIDUAL DE CLIENTES ]                                      |\n"
        " |   3. Buscar Cliente por RG (Encadeada)   |  4. Buscar Cliente por RG (Sequencial)        |\n"
        " |   7. Inserir Cliente no Fim (Encadeada)  |  8. Inserir Cliente no Fim (Sequencial)       |\n"
        " |   9. Inserir Cliente no Inicio (Encad.)  | 10. Inserir Cliente no Inicio (Sequencial)    |\n"
        " |  11. Inserir Cliente na Posicao N (Enc.) | 12. Inserir Cliente na Posicao N (Sequencial) |\n"
        " |  14. Remover da Posicao N (Encadeada)    | 13. Remover da Posicao N (Sequencial)         |\n"
        " +==========================================================================================+\n"
        " | [ BENCHMARKING PARALELO: COMPARACAO DE TEMPO (s), COMPARACOES C(n) E MOVIMENTACOES M(n) ]|\n"
        " |  15. Duelo de Leitura : Medir tempo de varredura e carga de arquivos de teste completos  |\n"
        " |  16. Duelo de Remocao : Deslocamento sequencial de memoria vs Ajuste de ponteiros (->)   |\n"
        " |  17. Duelo de Insercao (Inicio) : Empurrar vetor inteiro vs Redirecionar ponteiro inicio |\n"
        " |  18. Duelo de Insercao (Fim)    : Sobrecarga de realloc vs Navegacao ate o ponteiro nulo |\n"
        " |  19. Duelo de Insercao (Meio)   : Deslocamento parcial de memoria vs Iteracao de nos     |\n"
        " |  23. Duelo de Ordenacao : Selection Sort (Troca de valores de No vs Troca de Structs)    |\n"
        " +==========================================================================================+\n"
        " | [ CONTROLE DO SISTEMA ]                                                                  |\n"
        " |  22. Limpar as duas estruturas, formatar dados e liberar memoria alocada (free)          |\n"
        " | 167. Encerrar Aplicacao                                                                  |\n"
        " +==========================================================================================+\n"
        " \n >> Digite o numero da operacao desejada e pressione ENTER: "
    );
}